(function() {var implementors = {};
implementors["bitcrypto"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["chain"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["db"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["import"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["keys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["message"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["network"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["p2p"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["primitives"] = [];
implementors["rpc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"script/num/struct.Num.html\" title=\"struct script::num::Num\">Num</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];
implementors["script"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"script/struct.Num.html\" title=\"struct script::Num\">Num</a>",];
implementors["serialization"] = [];
implementors["verification"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"script/num/struct.Num.html\" title=\"struct script::num::Num\">Num</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
